### ISSUE TITLE
Install Virtualization Environment and Linux distribution in Virtualization Environment

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#11]
relates to #10 
The selected virtualization environment has to be installed and a Debian distribution such as [1] is to be installed. The steps to install the virtualization environment and the linux distribution have to documented for reproduction and later scripting

[1] https://www.raspberrypi.com/software/

epic #2

**Comment by cb6569** [comment]
Set-up debian based VM with virtual box to install Kanto.

**Comment by Smock001** [comment]
Some problems linked to the ssh encryption and to the debian packages occured.

**Comment by cb6569** [comment]
SSH encryption problem was solved. 
Installation works on Windows 10.
