### ISSUE TITLE
Install Eclipse Kanto in Linux distribution

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#12]
relates to #11 
in the linux distribution Eclipse Kanto needs to be installed. The installation has to be automated so that Kanto can automatically be installed in later stages. Automation can happen eg via bash scripting or tooling such as sensible etc.

epic #2

**Comment by cb6569** [comment]
https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Setting-up-Eclipse-Kanto-Runtime
