### ISSUE TITLE
Scripting to setup Eclipse Kanto environment on local machine

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#13]
Based on the previous steps a script has to be developed, which automatically sets up the virtualization environment, the linux distribution and Kanto inside the linux distribution so that a fully functioning Kanto instance is available on a local machine. Make sure that port forwarding rules, NATing to host etc is configured so that the Kanto instance can communicate with the cloud environment

epic #2

**Comment by cb6569** [comment]
Documentation in the wiki: https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Setting-up-Eclipse-Kanto-Runtime
Script: https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/tree/main/kanto-runtime

**Comment by cb6569** [comment]
Functioning on Windows 10, in some cases showing an error "box not found" on Windows 11. 
We will proceed without fixing the Windows 11 version error.
