### ISSUE TITLE
Build and install Kuksa.val

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#14]
Setup an build environment to be able to compile and build kuksa.val for later steps. Build Eclipse Kuksa.val and install it locally (no deployment into Kanto so far)

epic #3

**Comment by cb6569** [comment]
Check the existing repository for an image to build and install kuksa.val.
https://github.com/eclipse/kuksa.val/pkgs/container/kuksa.val%2Fkuksa-val

**Comment by cb6569** [comment]
Closed as container image is already provided by Kuksa project.
