### ISSUE TITLE
Configure Kuksa.val DBC feeder so that it replays available recording

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#15]
Kuksa.val allows to read low level data provider and translate it to W3C VISS format. Data from low level data provides can be recorded and replayed afterwards. 

Configure kuksa.val so that it can read the pre-recorded data from [1]. [2] contains hints on how to do so.

[1] https://github.com/eclipse/kuksa.val/blob/master/kuksa_feeders/dbc2val/candump-2021-12-08_151848.log.xz
[2] https://github.com/eclipse/kuksa.val/tree/master/kuksa_feeders/dbc2val

epic #3

**Comment by cb6569** [comment]
Check if DBC feeder is the relevant component or if the replay component fits better: https://github.com/eclipse/kuksa.val/tree/master/kuksa_feeders/replay

**Comment by max-grzanna** [comment]
* Container is running within kanto
* check with sample data needed

**Comment by Smock001** [comment]
It is working. Data transfer can be observed. Documentation created (see [Configure Kuksa.val DBC feeder](https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Configure-Kuksa.val-DBC-feeder)).

**Comment by Smock001** [comment]
A problem occurred linked to a newer version of the dbc feeder.

![Screenshot (40)](https://user-images.githubusercontent.com/50780911/183592911-f28d45be-18ed-4b94-aa0f-6c9a8adcd1ff.png)

**Comment by Smock001** [comment]
We decided to use the older version of the dbc feeder so far.
