### ISSUE TITLE
Build Kuksa.val image for Eclipse Kanto

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#16]
Kuksa val is about to run in a Eclipse Kanto environment. For that Kuksa.val has to be packaged in a container image.
Prepare an image of Kuksa val, which can be deployed in Eclipse Kanto.

Hint: Some parallel work takes place here, which might be contributed to Eclipse Kuksa soon. Check back on.the state prior start working on that.

epic #3

**Comment by cb6569** [comment]
Check the existing repository for an image to build and install kuksa.val.
https://github.com/eclipse/kuksa.val/pkgs/container/kuksa.val%2Fkuksa-val

**Comment by max-grzanna** [comment]
Image was already created and is now integrated into Eclipse Kanto.
