### ISSUE TITLE
Sketch Demo Application

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#17]
Eclipse Kuksa has several Demo applications [1]. based on those applications a Demo app has to be described. the description should only on a conceptual level, to allow an implementation in later steps.

[1] https://github.com/eclipse/kuksa.apps

epic #4

**Comment by cb6569** [comment]
Result of the story should be a wiki page with one or more ideas for a demo-application.

**Comment by max-grzanna** [comment]
- describe how the demo application should look like
- describe the flow of one data point through the whole application
- use a sequence diagram to model the application

**Comment by cb6569** [comment]
https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Sketch%20of%20Demo%20Application
