### ISSUE TITLE
Decide on Code repository

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#25]
Decide on where to store common code for the project. decide on whether one repo or several, where to store etc.

epic #5

**Comment by cb6569** [comment]
We decided to use the GitHub repository to have everything stored in one place and due to the simple editing because of the markdown format.

**Comment by max-grzanna** [comment]
For now, we decided to use one repository. If necessary, a second one will be set up.
