### ISSUE TITLE
Weekly protocol

### ISSUE THREAD

**Issue by max-grzanna** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#26]
# Weekly protocol
### Create a protocol once a week for the weekly meeting at the university.

Protocol 18.04.2022
[Protocol-180422.pdf](https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/files/8562872/Protocol-180422.pdf)

Epic #5

**Comment by max-grzanna** [comment]
Protocol 18.04.2022
[Protocol-18042022.pdf](https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/files/8550219/Protocol-18042022.pdf)

**Comment by bs-jokri** [comment]
@max-grzanna I would suggest to either write the protocol directly in the issue details field or setting up a dedicated wiki page and write the protocols there. This makes it easier to comment and collaborate on the content.

Remarks to the content of the protocol
1. We do not use a kanban board to organize the backlog. We use the kanban style board for the sprint backlog. The project backlog is managed as a scrum backlog without having different lanes for the state of the issues
2.  It is Eclipse Kuksa not Kuska
3. it is not a workload estimation but effort estimation. The difference is that the workload is what you make out of the efforts for an issue

**Comment by max-grzanna** [comment]
I am going to close this task, because the weekly protocol is no longer required for the university course.
