### ISSUE TITLE
Exchange Ambassador Component in Kuksa Cloud 

### ISSUE THREAD

**Issue by cb6569** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#27]
Kuksa Cloud contains an outdated component of Ambassador, needs to be replaced with a recent one. 
EPIC #1

**Comment by cb6569** [comment]
@bs-jokri contacted someone to support the solution process. 
@max-grzanna is in exchange with the contact person.

Time Boxing: Max. use of time 1 day

**Comment by cb6569** [comment]
https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Exchange-of-Ambassador-Component-in-Kuksa-Cloud-Project

**Comment by cb6569** [comment]
Ambassador Component was replaced with the respective Emissary Ingress versions. 
Some ports were eliminated (HTTP/HTTPS), might cause problems. 
Cluster is deployed, functionality has to be checked, especially Eclipse Hono.

**Comment by bs-jokri** [comment]
@max-grzanna would it makes sense to file a PR to Kuksa.cloud?

**Comment by cb6569** [comment]
Deployment is working.
Pull request will be issued after checking functionalities with Hono.
