### ISSUE TITLE
add ditto instance to kuksa.cloud for Kanto

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#31]
add ditto to kuksa helm chart as it might be used by Eclipse Kanto instance.

Epic: #1

**Comment by max-grzanna** [comment]
Some information about the integration of Eclipse Ditto into kuksa and k3s:

https://github.com/eclipse/ditto/blob/master/deployment/kubernetes/k3s/README.md

**Comment by cb6569** [comment]
Dependent on #32. Kanto runs not flawless, causes problems. 
Test if direct testing in VM is possible. 
Use of Emissary Ingress, Hono, Influx (in Hono integrated).
