### ISSUE TITLE
Establish connection between Cloud2edge and Kanto

### ISSUE THREAD

**Issue by max-grzanna** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#38]
Establish connection between Cloud2edge and Kanto.

**Comment by cb6569** [comment]
Problems in connecting with AMQP-Connector, port is unclear. 
Ongoing clarification with contact person.

**Comment by max-grzanna** [comment]
The connection is established and was successfully tested.

**Comment by bs-jokri** [comment]
Huray! Congrats our biggest obstacle seems to be out of the way!
