### ISSUE TITLE
Setup evaluated kubernetes distribution

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#7]
setup selected kubernetes distribution (eg k3s)
document setup process

epic #1

**Comment by max-grzanna** [comment]
The in #6 evaluated Distribution (K3s) was successfully set up on a Windows and Linux machine. The whole installation process is documented here: [Kubernetes distribution installation](https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Setting-up-Kubernetes)
