### ISSUE TITLE
Deploy Kuksa.cloud in local kubernetes cluster

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#8]
relates to #7 

run helm charts [1] to install kuksa cloud in local distribution.
Resource consumption might be to high for local deployment. Identify possible culprits and define strategies to strip down resource consumption.

[1] https://github.com/eclipse/kuksa.cloud/tree/master/deployment/helm

epic #1

**Comment by bs-jokri** [comment]
Spike Time boxed 1 day

**Comment by max-grzanna** [comment]
After fixing an indentation error inside the values.yaml file, the deployment of the helm chart seems to be successful. Further information can be found here: [Gitter](https://gitter.im/kuksa-val/community?at=6194b63db480cc50de59d559). 

Resource consumption is only high during the start of the installation of the helm chart. Note that Kubernetes version 1.16.15 was used to deploy the chart. Later versions cause problems regarding the used APIs and CustomResourceDefinitions.
