### ISSUE TITLE
Write scripting to setup kubernetes distribution and deployment of kuksa.cloud

### ISSUE THREAD

**Issue by bs-jokri** [max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension#9]
relates to #8, #7 

Write scripting (eg sh or use tools such as ansible) to setup the cloud part for the demo system.

epic #1

**Comment by cb6569** [comment]
Documentation in the wiki: https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/wiki/Setting-up-Kubernetes

Script: https://github.com/max-grzanna/Eclipse-Kuksa-Automotive-Edge-Extension/blob/main/install-kuksa.sh
